development:
  adapter: postgresql
  encoding: utf8
  database: music_grid_me_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: music_grid_me_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: music_grid_me
  pool: 5