# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43244f7d161ecd68ed96b5bc706c5209363d028f9670383ab371e02eb2d49a3c8d24705976edd7c19e8f21d00f36175aa61c57bbba94731200d91727d0d95d34
  facebook_id: 308994702596286
  facebook_secret: 86de1d669f33b02d1dd526b45659987d
test:
  secret_key_base: f5d29b6fc99d9ee64149d9a41e0ded1c42978829d916722877531b03e91f85263935d3341c9fc78a82a2604bb49939877b4f46f5575f473e3a8af6d800774d46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
